<h1><?= $exception->getMessage(); ?></h1>

<hr>

<?php

$arguments = [];

$argumentsList = function() use ($item, $arguments) {

    foreach ($item[0]['args'] as $key => $arg) {

        if (is_object($arg)) {
            $arg = '<span class="arg">(object)' . get_class($arg) . '</span>';
        } else if (is_array($arg)) {
            $arg = '<span class="arg">(array)[' . implode(', ', $arg) . ']</span>';
        } else {
            $arg = '<span class="arg">(string)\'' . $arg . '\'</span>';
        }

        $arguments[] = $arg;

    }

    return implode(', ', $arguments);

};

$s = 0;

foreach ($exception->getTrace() as $trace) {

    $codeBlock = $this->codeBlock($trace['file'], $trace['line']);
?>
    <div class="stack" id="<?= md5($trace['file'].$trace['line']); ?>"<?= $s === 0 ?: ' style="display: none;"'; ?>>

        <div class="sourceField">
            <b><?= $trace['file']; ?>:<?= $trace['line'] ?></b>
        </div>

        <div class="codeBlock">
            <code>
                <?= $codeBlock; ?>
            </code>
        </div>

    </div>

<?php
    $s++;
}
?>

<hr>

<h2>$_GET</h2>
<div class="serverData">

    <?php

    if (empty($_GET)) {
    ?>
        No data found...
    <?php
    }

    foreach ($_GET as $gkey => $gvalue) { ?>

        <div class="row">
            <div class="cell width-30"><?= $gkey; ?></div>
            <div class="cell"><?= $gvalue; ?></div>
        </div>

    <?php
    }
    ?>

</div>

<hr>

<h2>$_POST</h2>
<div class="serverData">
    <?php

    if (empty($_POST)) {
        ?>
        No data found...
        <?php
    }

    foreach ($_POST as $pkey => $pvalue) { ?>

        <div class="row">
            <div class="cell width-30"><?= $pkey; ?></div>
            <div class="cell"><?= $pvalue; ?></div>
        </div>

    <?php
    }
    ?>

</div>

<hr>

<h2>$_SERVER</h2>
<div class="serverData">

    <?php
    foreach ($_SERVER as $skey => $svalue) { ?>

        <div class="row">
            <div class="cell width-30"><?= $skey; ?></div>
            <div class="cell"><?= $svalue; ?></div>
        </div>

    <?php
    }
    ?>

</div>